<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="component" nsURI="http://www.dfki.de/iui/basys/model/component"
    nsPrefix="component">
  <eAnnotations source="http://de.dfki.iui.mmds/CoreModel"/>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentResponse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//ResponseStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusCode" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//ComponentRequest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputParameters" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestStatus">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="ACCEPTED" value="1"/>
    <eLiterals name="REJECTED" value="2"/>
    <eLiterals name="NOOP" value="3" literal="NOOP"/>
    <eLiterals name="QUEUED" value="4" literal="QUEUED"/>
    <eLiterals name="DONE" value="5" literal="DONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResponseStatus">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="OK" value="1"/>
    <eLiterals name="NOT_OK" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//VariableType"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="NULL" literal=""/>
    <eLiterals name="BOOLEAN" value="1"/>
    <eLiterals name="INTEGER" value="2"/>
    <eLiterals name="STRING" value="3"/>
    <eLiterals name="DOUBLE" value="4"/>
    <eLiterals name="LONG" value="5"/>
    <eLiterals name="DATE" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionState">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="CLEARING" value="1"/>
    <eLiterals name="STOPPED" value="2"/>
    <eLiterals name="STARTING" value="3"/>
    <eLiterals name="IDLE" value="4"/>
    <eLiterals name="SUSPENDED" value="5"/>
    <eLiterals name="EXECUTE" value="6"/>
    <eLiterals name="STOPPING" value="7"/>
    <eLiterals name="ABORTING" value="8"/>
    <eLiterals name="ABORTED" value="9"/>
    <eLiterals name="HOLDING" value="10"/>
    <eLiterals name="HELD" value="11"/>
    <eLiterals name="UNHOLDING" value="12"/>
    <eLiterals name="SUSPENDING" value="13"/>
    <eLiterals name="UNSUSPENDING" value="14"/>
    <eLiterals name="RESETTING" value="15"/>
    <eLiterals name="COMPLETING" value="16"/>
    <eLiterals name="COMPLETE" value="17"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionMode">
    <eLiterals name="PRODUCTION"/>
    <eLiterals name="MAINTENANCE" value="1"/>
    <eLiterals name="MANUAL" value="2"/>
    <eLiterals name="CHANGE_OVER" value="3"/>
    <eLiterals name="CLEAN" value="4"/>
    <eLiterals name="SET_UP" value="5"/>
    <eLiterals name="EMPTY_OUT" value="6"/>
    <eLiterals name="SIMULATION" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExecutionCommand">
    <eLiterals name="RESET"/>
    <eLiterals name="START" value="1"/>
    <eLiterals name="STOP" value="2"/>
    <eLiterals name="HOLD" value="3"/>
    <eLiterals name="UNHOLD" value="4" literal="UNHOLD"/>
    <eLiterals name="SUSPEND" value="5"/>
    <eLiterals name="UNSUSPEND" value="6"/>
    <eLiterals name="ABORT" value="7"/>
    <eLiterals name="CLEAR" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OccupationLevel">
    <eLiterals name="FREE"/>
    <eLiterals name="OCCUPIED" value="1"/>
    <eLiterals name="PRIORITY" value="2"/>
    <eLiterals name="LOCAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRequestCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentRequests" upperBound="-1"
        eType="#//ComponentRequest" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRequest" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correlationId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occupierId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRequestStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//RequestStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusRequest" eSuperTypes="#//ComponentRequest"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupationLevelRequest" eSuperTypes="#//ComponentRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occupationLevel" eType="#//OccupationLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionModeRequest" eSuperTypes="#//ComponentRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionMode" eType="#//ExecutionMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionCommandRequest" eSuperTypes="#//ComponentRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionCommand" eType="#//ExecutionCommand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationModeRequest" eSuperTypes="#//ComponentRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationMode" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputParameters" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputParameters" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
