<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="processinstance" nsURI="http://www.dfki.de/iui/basys/model/processinstance"
    nsPrefix="processinstance">
  <eAnnotations source="http://de.dfki.iui.mmds/CoreModel"/>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessInstance" eSuperTypes="../../de.dfki.cos.basys.platform.model.base/model/base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processDefinition" lowerBound="1"
        eType="ecore:EClass processdefinition.ecore#//ProcessDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" lowerBound="1" eType="ecore:EClass order.ecore#//Order"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productInstance" eType="ecore:EClass productinstance.ecore#//ProductInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskInstances" upperBound="-1"
        eType="#//TaskInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskInstance" eSuperTypes="../../de.dfki.cos.basys.platform.model.base/model/base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EEnum processdefinition.ecore#//TaskStateEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="ecore:EClass processdefinition.ecore#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessInstanceStore">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processInstances" upperBound="-1"
        eType="#//ProcessInstance" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
