<?xml version="1.0" encoding="UTF-8"?>
<resource:ResourceTypeCatalogue xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:resource="http://www.dfki.de/iui/basys/model/resource">
  <resourceTypes xsi:type="resource:Tool" id="_yIFSQjB3Eei1bbwBPPZWOA" name="Festo"/>
  <resourceTypes xsi:type="resource:Machine" id="_AgTVCzB4Eei1bbwBPPZWOA"/>
</resource:ResourceTypeCatalogue>
