/**
 */
package de.dfki.iui.basys.model.domain.topology.provider;

import de.dfki.iui.basys.model.domain.topology.util.TopologyAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TopologyItemProviderAdapterFactory extends TopologyAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TopologyItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Enterprise} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnterpriseItemProvider enterpriseItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Enterprise}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnterpriseAdapter() {
		if (enterpriseItemProvider == null) {
			enterpriseItemProvider = new EnterpriseItemProvider(this);
		}

		return enterpriseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Site} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SiteItemProvider siteItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Site}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSiteAdapter() {
		if (siteItemProvider == null) {
			siteItemProvider = new SiteItemProvider(this);
		}

		return siteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Area} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AreaItemProvider areaItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Area}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAreaAdapter() {
		if (areaItemProvider == null) {
			areaItemProvider = new AreaItemProvider(this);
		}

		return areaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.ProcessCell} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessCellItemProvider processCellItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.ProcessCell}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessCellAdapter() {
		if (processCellItemProvider == null) {
			processCellItemProvider = new ProcessCellItemProvider(this);
		}

		return processCellItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.ProductionUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductionUnitItemProvider productionUnitItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.ProductionUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductionUnitAdapter() {
		if (productionUnitItemProvider == null) {
			productionUnitItemProvider = new ProductionUnitItemProvider(this);
		}

		return productionUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.ProductionLine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductionLineItemProvider productionLineItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.ProductionLine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductionLineAdapter() {
		if (productionLineItemProvider == null) {
			productionLineItemProvider = new ProductionLineItemProvider(this);
		}

		return productionLineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.StorageZone} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorageZoneItemProvider storageZoneItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.StorageZone}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorageZoneAdapter() {
		if (storageZoneItemProvider == null) {
			storageZoneItemProvider = new StorageZoneItemProvider(this);
		}

		return storageZoneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Unit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitItemProvider unitItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Unit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAdapter() {
		if (unitItemProvider == null) {
			unitItemProvider = new UnitItemProvider(this);
		}

		return unitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.WorkCell} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkCellItemProvider workCellItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.WorkCell}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkCellAdapter() {
		if (workCellItemProvider == null) {
			workCellItemProvider = new WorkCellItemProvider(this);
		}

		return workCellItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.StorageUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorageUnitItemProvider storageUnitItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.StorageUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorageUnitAdapter() {
		if (storageUnitItemProvider == null) {
			storageUnitItemProvider = new StorageUnitItemProvider(this);
		}

		return storageUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Station} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StationItemProvider stationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Station}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStationAdapter() {
		if (stationItemProvider == null) {
			stationItemProvider = new StationItemProvider(this);
		}

		return stationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Transition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionItemProvider transitionItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionAdapter() {
		if (transitionItemProvider == null) {
			transitionItemProvider = new TransitionItemProvider(this);
		}

		return transitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.AssemblyStation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssemblyStationItemProvider assemblyStationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.AssemblyStation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssemblyStationAdapter() {
		if (assemblyStationItemProvider == null) {
			assemblyStationItemProvider = new AssemblyStationItemProvider(this);
		}

		return assemblyStationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.BufferStation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BufferStationItemProvider bufferStationItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.BufferStation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBufferStationAdapter() {
		if (bufferStationItemProvider == null) {
			bufferStationItemProvider = new BufferStationItemProvider(this);
		}

		return bufferStationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.ProcessUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessUnitItemProvider processUnitItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.ProcessUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessUnitAdapter() {
		if (processUnitItemProvider == null) {
			processUnitItemProvider = new ProcessUnitItemProvider(this);
		}

		return processUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.DiscreteManufacturingEquipmentModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiscreteManufacturingEquipmentModuleItemProvider discreteManufacturingEquipmentModuleItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.DiscreteManufacturingEquipmentModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiscreteManufacturingEquipmentModuleAdapter() {
		if (discreteManufacturingEquipmentModuleItemProvider == null) {
			discreteManufacturingEquipmentModuleItemProvider = new DiscreteManufacturingEquipmentModuleItemProvider(this);
		}

		return discreteManufacturingEquipmentModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Tool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolItemProvider toolItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Tool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolAdapter() {
		if (toolItemProvider == null) {
			toolItemProvider = new ToolItemProvider(this);
		}

		return toolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.StationaryTool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StationaryToolItemProvider stationaryToolItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.StationaryTool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStationaryToolAdapter() {
		if (stationaryToolItemProvider == null) {
			stationaryToolItemProvider = new StationaryToolItemProvider(this);
		}

		return stationaryToolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.MovableTool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MovableToolItemProvider movableToolItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.MovableTool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMovableToolAdapter() {
		if (movableToolItemProvider == null) {
			movableToolItemProvider = new MovableToolItemProvider(this);
		}

		return movableToolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Transport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransportItemProvider transportItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Transport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransportAdapter() {
		if (transportItemProvider == null) {
			transportItemProvider = new TransportItemProvider(this);
		}

		return transportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Storage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorageItemProvider storageItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Storage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorageAdapter() {
		if (storageItemProvider == null) {
			storageItemProvider = new StorageItemProvider(this);
		}

		return storageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Fixture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FixtureItemProvider fixtureItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Fixture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFixtureAdapter() {
		if (fixtureItemProvider == null) {
			fixtureItemProvider = new FixtureItemProvider(this);
		}

		return fixtureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Gate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GateItemProvider gateItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Gate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGateAdapter() {
		if (gateItemProvider == null) {
			gateItemProvider = new GateItemProvider(this);
		}

		return gateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Robot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RobotItemProvider robotItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Robot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRobotAdapter() {
		if (robotItemProvider == null) {
			robotItemProvider = new RobotItemProvider(this);
		}

		return robotItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Carrier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarrierItemProvider carrierItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Carrier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCarrierAdapter() {
		if (carrierItemProvider == null) {
			carrierItemProvider = new CarrierItemProvider(this);
		}

		return carrierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Machine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MachineItemProvider machineItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Machine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMachineAdapter() {
		if (machineItemProvider == null) {
			machineItemProvider = new MachineItemProvider(this);
		}

		return machineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.StaticObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticObjectItemProvider staticObjectItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.StaticObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticObjectAdapter() {
		if (staticObjectItemProvider == null) {
			staticObjectItemProvider = new StaticObjectItemProvider(this);
		}

		return staticObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Turnable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnableItemProvider turnableItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Turnable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnableAdapter() {
		if (turnableItemProvider == null) {
			turnableItemProvider = new TurnableItemProvider(this);
		}

		return turnableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Conveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConveyorItemProvider conveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Conveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConveyorAdapter() {
		if (conveyorItemProvider == null) {
			conveyorItemProvider = new ConveyorItemProvider(this);
		}

		return conveyorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.LiftingTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiftingTableItemProvider liftingTableItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.LiftingTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiftingTableAdapter() {
		if (liftingTableItemProvider == null) {
			liftingTableItemProvider = new LiftingTableItemProvider(this);
		}

		return liftingTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.AVG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AVGItemProvider avgItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.AVG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAVGAdapter() {
		if (avgItemProvider == null) {
			avgItemProvider = new AVGItemProvider(this);
		}

		return avgItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Transposer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransposerItemProvider transposerItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Transposer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransposerAdapter() {
		if (transposerItemProvider == null) {
			transposerItemProvider = new TransposerItemProvider(this);
		}

		return transposerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.CarrierHandlingSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CarrierHandlingSystemItemProvider carrierHandlingSystemItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.CarrierHandlingSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCarrierHandlingSystemAdapter() {
		if (carrierHandlingSystemItemProvider == null) {
			carrierHandlingSystemItemProvider = new CarrierHandlingSystemItemProvider(this);
		}

		return carrierHandlingSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Lift} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiftItemProvider liftItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Lift}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiftAdapter() {
		if (liftItemProvider == null) {
			liftItemProvider = new LiftItemProvider(this);
		}

		return liftItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.VerticalTransport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VerticalTransportItemProvider verticalTransportItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.VerticalTransport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVerticalTransportAdapter() {
		if (verticalTransportItemProvider == null) {
			verticalTransportItemProvider = new VerticalTransportItemProvider(this);
		}

		return verticalTransportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.HorizontalTransport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HorizontalTransportItemProvider horizontalTransportItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.HorizontalTransport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHorizontalTransportAdapter() {
		if (horizontalTransportItemProvider == null) {
			horizontalTransportItemProvider = new HorizontalTransportItemProvider(this);
		}

		return horizontalTransportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Rollerbed} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RollerbedItemProvider rollerbedItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Rollerbed}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRollerbedAdapter() {
		if (rollerbedItemProvider == null) {
			rollerbedItemProvider = new RollerbedItemProvider(this);
		}

		return rollerbedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Loader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoaderItemProvider loaderItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Loader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoaderAdapter() {
		if (loaderItemProvider == null) {
			loaderItemProvider = new LoaderItemProvider(this);
		}

		return loaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Unloader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnloaderItemProvider unloaderItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Unloader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnloaderAdapter() {
		if (unloaderItemProvider == null) {
			unloaderItemProvider = new UnloaderItemProvider(this);
		}

		return unloaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.BodyStore} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BodyStoreItemProvider bodyStoreItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.BodyStore}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBodyStoreAdapter() {
		if (bodyStoreItemProvider == null) {
			bodyStoreItemProvider = new BodyStoreItemProvider(this);
		}

		return bodyStoreItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.Clamp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClampItemProvider clampItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.Clamp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClampAdapter() {
		if (clampItemProvider == null) {
			clampItemProvider = new ClampItemProvider(this);
		}

		return clampItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.BeltConveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BeltConveyorItemProvider beltConveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.BeltConveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBeltConveyorAdapter() {
		if (beltConveyorItemProvider == null) {
			beltConveyorItemProvider = new BeltConveyorItemProvider(this);
		}

		return beltConveyorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.RollConveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RollConveyorItemProvider rollConveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.RollConveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRollConveyorAdapter() {
		if (rollConveyorItemProvider == null) {
			rollConveyorItemProvider = new RollConveyorItemProvider(this);
		}

		return rollConveyorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.ChainConveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChainConveyorItemProvider chainConveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.ChainConveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChainConveyorAdapter() {
		if (chainConveyorItemProvider == null) {
			chainConveyorItemProvider = new ChainConveyorItemProvider(this);
		}

		return chainConveyorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.PalletConveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PalletConveyorItemProvider palletConveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.PalletConveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPalletConveyorAdapter() {
		if (palletConveyorItemProvider == null) {
			palletConveyorItemProvider = new PalletConveyorItemProvider(this);
		}

		return palletConveyorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.dfki.iui.basys.model.domain.topology.OverheadConveyor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OverheadConveyorItemProvider overheadConveyorItemProvider;

	/**
	 * This creates an adapter for a {@link de.dfki.iui.basys.model.domain.topology.OverheadConveyor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOverheadConveyorAdapter() {
		if (overheadConveyorItemProvider == null) {
			overheadConveyorItemProvider = new OverheadConveyorItemProvider(this);
		}

		return overheadConveyorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (enterpriseItemProvider != null) enterpriseItemProvider.dispose();
		if (siteItemProvider != null) siteItemProvider.dispose();
		if (areaItemProvider != null) areaItemProvider.dispose();
		if (processCellItemProvider != null) processCellItemProvider.dispose();
		if (productionUnitItemProvider != null) productionUnitItemProvider.dispose();
		if (productionLineItemProvider != null) productionLineItemProvider.dispose();
		if (storageZoneItemProvider != null) storageZoneItemProvider.dispose();
		if (unitItemProvider != null) unitItemProvider.dispose();
		if (workCellItemProvider != null) workCellItemProvider.dispose();
		if (storageUnitItemProvider != null) storageUnitItemProvider.dispose();
		if (stationItemProvider != null) stationItemProvider.dispose();
		if (transitionItemProvider != null) transitionItemProvider.dispose();
		if (assemblyStationItemProvider != null) assemblyStationItemProvider.dispose();
		if (bufferStationItemProvider != null) bufferStationItemProvider.dispose();
		if (processUnitItemProvider != null) processUnitItemProvider.dispose();
		if (discreteManufacturingEquipmentModuleItemProvider != null) discreteManufacturingEquipmentModuleItemProvider.dispose();
		if (toolItemProvider != null) toolItemProvider.dispose();
		if (stationaryToolItemProvider != null) stationaryToolItemProvider.dispose();
		if (movableToolItemProvider != null) movableToolItemProvider.dispose();
		if (transportItemProvider != null) transportItemProvider.dispose();
		if (storageItemProvider != null) storageItemProvider.dispose();
		if (fixtureItemProvider != null) fixtureItemProvider.dispose();
		if (gateItemProvider != null) gateItemProvider.dispose();
		if (robotItemProvider != null) robotItemProvider.dispose();
		if (carrierItemProvider != null) carrierItemProvider.dispose();
		if (machineItemProvider != null) machineItemProvider.dispose();
		if (staticObjectItemProvider != null) staticObjectItemProvider.dispose();
		if (turnableItemProvider != null) turnableItemProvider.dispose();
		if (conveyorItemProvider != null) conveyorItemProvider.dispose();
		if (liftingTableItemProvider != null) liftingTableItemProvider.dispose();
		if (avgItemProvider != null) avgItemProvider.dispose();
		if (transposerItemProvider != null) transposerItemProvider.dispose();
		if (carrierHandlingSystemItemProvider != null) carrierHandlingSystemItemProvider.dispose();
		if (liftItemProvider != null) liftItemProvider.dispose();
		if (verticalTransportItemProvider != null) verticalTransportItemProvider.dispose();
		if (horizontalTransportItemProvider != null) horizontalTransportItemProvider.dispose();
		if (rollerbedItemProvider != null) rollerbedItemProvider.dispose();
		if (loaderItemProvider != null) loaderItemProvider.dispose();
		if (unloaderItemProvider != null) unloaderItemProvider.dispose();
		if (bodyStoreItemProvider != null) bodyStoreItemProvider.dispose();
		if (clampItemProvider != null) clampItemProvider.dispose();
		if (beltConveyorItemProvider != null) beltConveyorItemProvider.dispose();
		if (rollConveyorItemProvider != null) rollConveyorItemProvider.dispose();
		if (chainConveyorItemProvider != null) chainConveyorItemProvider.dispose();
		if (palletConveyorItemProvider != null) palletConveyorItemProvider.dispose();
		if (overheadConveyorItemProvider != null) overheadConveyorItemProvider.dispose();
	}

}
