<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="layout" nsURI="http://www.dfki.de/iui/basys/model/layout" nsPrefix="layout">
  <eClassifiers xsi:type="ecore:EClass" name="ProductionLineLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" eType="#//LayoutElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutElement" eSuperTypes="../../de.dfki.cos.basys.platform.model.base/model/base.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topologyElement" eType="ecore:EClass topology.ecore#//TopologyElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position"/>
  </eClassifiers>
</ecore:EPackage>
